# Generated by Django 5.1.1 on 2024-10-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.AlterModelOptions(
            name="good",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
        migrations.AddField(
            model_name="good",
            name="alternative_text",
            field=models.CharField(
                blank=True,
                help_text="Для фото (важно для SEO и доступности)",
                max_length=255,
                verbose_name="Альтернативный текст",
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="description",
            field=models.TextField(
                blank=True, max_length=1000, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="good",
            name="img_caption",
            field=models.CharField(
                blank=True,
                help_text="Для фото",
                max_length=255,
                verbose_name="Подпись",
            ),
        ),
    ]
