# Generated by Django 5.1.1 on 2024-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="good",
            name="availability",
            field=models.BooleanField(default=False, verbose_name="Наличие"),
        ),
    ]
