# Generated by Django 5.1.1 on 2024-10-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_good_availability"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="good",
            name="slug",
            field=models.CharField(default="", max_length=255),
        ),
    ]
