# Generated by Django 5.1.1 on 2024-10-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_category_options_alter_good_options_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "Элемент заказа",
                "verbose_name_plural": "Элементы заказа",
            },
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="goods.good",
                verbose_name="Продукт",
            ),
        ),
    ]
